### PR TITLE
Add two new perltidy options.

### PR DESCRIPTION
**Pull request by drgrice1**
First add the extended continuation indentation option. I added this to
the webwork2 and pg .perltidyrc files, and it does a better job of
indenting for nested structures.  This rule responsible for the changes
to the other files in this pull request.

Second add the option to disable vertical alignment of qw quotes.  Since
this option is added, the workflow version of perltidy can now be
allowed to increase.  I left the lock though, and just moved it to the
newest version.

### CODE REVIEW

**Comment by drgrice1** [comment]
Actually, you don't need to. With the qw option added, there is no difference in the result.

**Comment by pstaabp** [comment]
And the only files affected by the `xci` option are those in the PR. Correct?

**Comment by drgrice1** [comment]
Yep.

**Review by pstaabp — APPROVED** [review]
Looks good and I think the additional nesting is easier to read.

**Comment by drgrice1** [comment]
And the change is an improvement in those cases in my opinion also. That is why I had added it to the WeBWorK and pg rules.

**Pull request merged**
