### PR TITLE
Render no iframe update

### PR DESCRIPTION
**Pull request by drgrice1**
This builds on @drdrew42's pull request for rendering problems without iframes.  It is still a work in progress of course.

For everything to work you will need some changes to the renderer and pg.  These changes are in the ww3-rendering-work branch of my fork of the renderer.  Make sure to run `git submodules update` after switching to that branch to also get my branch of pg with the necessary changes there.

### CODE REVIEW

**Comment by drgrice1** [comment]
Note you will need to run `npm install` to update node dependencies for this also.

**Comment by pstaabp** [comment]
Seems to be working well on basic problems. 

On a problem with a graph, like: `Library/Mizzou/Algebra/eqns_systems_solving/eqns_systems_graph_01.pg` the graph isn't shown.  It is generated in my webwork2 directory inside `htdocs/tmp/renderer/images` but not properly returned to the client.  

Also, I notice problems with non-standard macros , that I'm getting errors in the mojolicious console like 
```
Can't locate macro file |AnswerFormatHelp.pl| via path: |.|,<br/> |[TMPL]/macros|,<br/> |[PG]/macros/|,<br/> |[TMPL]/Library/macros/Alfred|,<br/> |[TMPL]/Library/macros/BrockPhysics|,<br/> |[TMPL]/Library/macros/CollegeOfIdaho|,<br/> |[TMPL]/Library/macros/Dartmouth|,<br/> |[TMPL]/Library/macros/FortLewis|,<br/> |[TMPL]/Library/macros/Hope|,<br/> |[TMPL]/Library/macros/LaTech|,<br/> |[TMPL]/Library/macros/MC|,<br/> |[TMPL]/Library/macros/Michigan|,<br/> |[TMPL]/Library/macros/Mizzou|,<br/> |[TMPL]/Library/macros/NAU|,<br/> |[TMPL]/Library/macros/PCC|,<br/> |[TMPL]/Library/macros/TCNJ|,<br/> |[TMPL]/Library/macros/UBC|,<br/> |[TMPL]/Library/macros/UMass-Amherst|,<br/> |[TMPL]/Library/macros/UW-Stout|,<br/> |[TMPL]/Library/macros/UniSiegen|,<br/> |[TMPL]/Library/macros/Union|,<br/> |[TMPL]/Library/macros/WHFreeman|,<br/> |[TMPL]/Library/macros/Wiley|,<br/> |[TMPL]/Contrib/CAPA/macros/CAPA_Tools|,<br/> |[TMPL]/Contrib/CAPA/macros/CAPA_MCTools|,<br/> |[TMPL]/Contrib/CAPA/macros/CAPA_Tools|,<br/> |[TMPL]/Contrib/CAPA/macros/CAPA_MCTools|=
```

this looks like it is looking in a courses/templates directory.

**Comment by drgrice1** [comment]
@pstaabp:  It looks like you forgot to unset your WEBWORK_ROOT environment variable again.

@drdrew42:  Perhaps it is not a good idea for the standalone renderer to use this same environment variable.

**Comment by pstaabp** [comment]
@drgrice1 most excellent!!  graphs show up and no macros error.

**Comment by pstaabp** [comment]
Another error I noticed.   On `Library/Mizzou/Algebra/eqns_systems_solving/eqns_systems_graph_01.pg`, 
I'm getting: 
```
Use of uninitialized value in concatenation (.) or string at /opt/webwork/renderer/lib/RenderApp/Model/Problem.pm line 258 during global destruction.
        (in cleanup)    (in cleanup)  at /opt/webwork/renderer/lib/RenderApp/Model/Problem.pm line 262 during global destruction.
```

**Comment by pstaabp** [comment]
One other thing.  I'm trying a tikz problem (the test one that you wrote @drgrice1 with the two bar plots).  I'm not getting the images though.  Where are they being written?  (I know we were discussing this yesterday).

**Comment by drgrice1** [comment]
> Another error I noticed. On `Library/Mizzou/Algebra/eqns_systems_solving/eqns_systems_graph_01.pg`,
> I'm getting:
> 
> ```
> Use of uninitialized value in concatenation (.) or string at /opt/webwork/renderer/lib/RenderApp/Model/Problem.pm line 258 during global destruction.
>         (in cleanup)    (in cleanup)  at /opt/webwork/renderer/lib/RenderApp/Model/Problem.pm line 262 during global destruction.
> ```

This problem does that with webwork2 as well.  Check your apache2 error log.  With the standalone renderer you get that in your console instead.

**Comment by drgrice1** [comment]
> One other thing. I'm trying a tikz problem (the test one that you wrote @drgrice1 with the two bar plots). I'm not getting the images though. Where are they being written? (I know we were discussing this yesterday).

The tex files are first written to lib/WeBWorK/tmp.  Note that if that directory does not exist, then the files will not be written, and no images will be generated.  The renderer does not have that directory, so you will need to create it.  Then the generated image is written to lib/WeBWorK/htdocs/tmp.  In my testing of this, the image is generated in lib/WeBWorK/htdocs/tmp, but morbo hot reloads due to files being written in the lib directory, and the request does not complete.  So you don't get the image in ww3.  However, if you load the problem again it will work, as the cached image is used, and nothing is written in the lib directory.

**Comment by drgrice1** [comment]
> ```
> Use of uninitialized value in concatenation (.) or string at /opt/webwork/renderer/lib/RenderApp/Model/Problem.pm line 258 during global destruction.
>         (in cleanup)    (in cleanup)  at /opt/webwork/renderer/lib/RenderApp/Model/Problem.pm line 262 during global destruction.
> ```

The reason this occurs is that the problem has the following line:
```perl
\{ image( insertGraph($graph), width=>$gridWidth, height=>$gridHeight, tex_size=>800 ) \}
```
The variables `$gridWidth` and `$gridHeight` are not defined anywhere in the problem.

Also, I believe that the reason for the next line you are showing, the line `(in cleanup) ...` is due to morbo hot reloading after the generated image is written in lib/WeBWorK/htdocs/tmp.  So the same issue as with the TikZ images.  If this problem is not loading for you, that is why.  The problem does load for me, but it may be a timing issue relative to the hot reload of morbo that it works for me.

**Comment by drgrice1** [comment]
By the way, I fixed the hot reload issue for me by creating the directory tmp in the root directory of the renderer git clone, and then linking to that in lib/WeBWorK.  I also created a subdirectory tmp/renderer in the first tmp directory, and linked to that in lib/WeBWorK/htdocs/tmp.

**Comment by pstaabp** [comment]
@drgrice1 @drdrew42  What do think about merging this in?  It seems like the no-iframe method will work and I think this is in shape to do so.

**Comment by drgrice1** [comment]
I am good with that.

**Review by drdrew42 — APPROVED** [review]
Yeah, I've been using this branch -- it's ready!

**Comment by drdrew42** [comment]
Thanks @drgrice1 🥳  -- this was no small undertaking, and the payoff is impressively fast problem loads!

**Pull request merged**
