### PR TITLE
update badges to correctly link CI, codecov and activity

### PR DESCRIPTION
**Pull request by eltenedor**
token for the badge needs to be adapted

### CODE REVIEW

**Comment by eltenedor** [comment]
# Todo's before this branch can be merged into main

- [ ] Add the correct `CODECOV_TOKEN` as repository secret to `openwebwork/webwork3`. This token can be retrieved from https://app.codecov.io/gh/openwebwork/webwork3/settings (cf. https://github.com/eltenedor/coverage#prerequesites)
- [ ] Complete the badge in the readme with the correct token. Retrieve markdown for the badge at https://app.codecov.io/gh/openwebwork/webwork3/settings/badge

**Comment by drgrice1** [comment]
Add fix lint in pull request to your todo.

**Comment by eltenedor** [comment]
@drgrice1 
> Add fix lint in pull request to your todo.

Fixed. It was due to a line that was too long in README.md

**Comment by drgrice1** [comment]
Thanks for fixing the lint.

Is there any way to either make the unit tests and coverage badge not a link or a link to something that is not just the badge?

For the last commit badge, is there a way to make it a link to the actual last commit?

**Comment by eltenedor** [comment]
> Thanks for fixing the lint.
> 
> Is there any way to either make the unit tests and coverage badge not a link or a link to something that is not just the badge?
> 
> For the last commit badge, is there a way to make it a link to the actual last commit?

Yes there is. You can use the image .svg and use it like a regular link, e.g.
```
 [![image alt text](image url link)](anchor link)
```

https://www.w3schools.io/file/markdown-images/

**Comment by eltenedor** [comment]
> > Thanks for fixing the lint.
> > Is there any way to either make the unit tests and coverage badge not a link or a link to something that is not just the badge?
> > For the last commit badge, is there a way to make it a link to the actual last commit?
> 
> Yes there is. You can use the image .svg and use it like a regular link, e.g.
> 
> ```
>  [image alt text](anchor link)
> ```
> 
> https://www.w3schools.io/file/markdown-images/

I'll check if there is a link that always points to the latest commit. This would make the badge more useful.

**Comment by drgrice1** [comment]
> Yes there is. You can use the image .svg and use it like a regular link, e.g.
> 
> ```
>  [image alt text](anchor link)
> ```

Yeah, I know that.  I guess I phrased my question incorrectly.  I meant is there a good location to point to links to, rather than linking to the image.  I think it is a bit annoying that Github image markdown is always a link to the image.

**Comment by eltenedor** [comment]
>  I think it is a bit annoying that Github image markdown is always a link to the image.

I agree. I'll add also a link to the codecov site

**Comment by drgrice1** [comment]
How about instead of linking to the super linter webpage you link to the actual action.  The link for that is https://github.com/openwebwork/webwork3/actions/workflows/linter.yml.  Then do the same with the unit tests workflow.

**Comment by eltenedor** [comment]
> How about instead of linking to the super linter webpage you link to the actual action. The link for that is https://github.com/openwebwork/webwork3/actions/workflows/linter.yml. Then do the same with the unit tests workflow.

Yes, this should work.

**Comment by eltenedor** [comment]
For the other todos someone with permission to access to the `openwebwork/webwork3` secrets and to the page 

https://app.codecov.io/gh/openwebwork/webwork3/settings 

needs to take over. It should be straightforward.

**Comment by drgrice1** [comment]
The codecov repository secret is set, but the unit-tests workflow still fails with this.

**Comment by eltenedor** [comment]
> The codecov repository secret is set, but the unit-tests workflow still fails with this.

I still suppose that something has not been set correctly. I just tried it out on my end (pull request to my fork of this repo) and it runs fine:

https://github.com/eltenedor/webwork3/pull/1/checks?check_run_id=3407517120

image


Did you follow the instructions here?

https://github.com/eltenedor/coverage/blob/main/README.md#prerequesites

They worked out fine for me.

**Comment by drgrice1** [comment]
@pstaabp already had added the codecov token to this repositories secrets.  I copied it in again just to be sure.  Clearly this doesn't just make it work.  Something else needs to be done.

**Comment by drgrice1** [comment]
I think the problem is this statement
>With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
from https://docs.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

This means that this is not something we want to do in a workflow that is triggered for pull requests.  So if we want the unit tests run for pull requests and also want to upload coverage reports, then we are going to need to do things differently.  Either we will need two workflows or make the part that uploads the coverage report only run when the pull request is merged.

**Comment by eltenedor** [comment]
@drgrice1 it should work now. Do you have access to the token that is needed for the badge? This should take care of the last todo. It's located on

https://app.codecov.io/gh/openwebwork/webwork3/settings/badge

For one of my repositories it looks like this.

image

**Comment by drgrice1** [comment]
Yeah.  The link is ```[codecov](https://codecov.io/gh/openwebwork/webwork3)```

or in action

[codecov](https://codecov.io/gh/openwebwork/webwork3)

**Comment by drgrice1** [comment]
This looks good.  I will merge this in.  This is the final test of this pull request, and can only be done by merging.  When this occurs the unit test workflow should run again, and the code coverage should be uploaded.

**Comment by drgrice1** [comment]
It worked as expected!

**Pull request merged**
